services:
  - type: web
    name: UOB Landscape
    env: php
    region: frankfurt
    plan: free
    buildCommand: "composer install"
    startCommand: "php -S 0.0.0.0:$PORT"
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false