services:
  - type: web
    name: uob-landscape
    env: node
    region: frankfurt
    plan: free
    buildCommand: "apt-get update && apt-get install -y php php-cli php-mbstring && composer install"
    startCommand: "php -S 0.0.0.0:$PORT"
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false